version: "3.4"

services:
  localidade-db:
    image: postgres:14.5
    container_name: localidade-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localidade
    ports:
      - 8090:5432
    networks:
      - project107_net

networks:
  project107_net:
    name: project107_net
    driver: bridge
