version: "3.4"

services:
  database:
    container_name: project107_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project107_net
    volumes:
      - project107_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localidade

networks:
  project107_net:
    name: project107_net
    driver: bridge
