version: "3.4"

services:
  database:
    container_name: project107_database
    image: postgres:14.5
    restart: always
    ports:
      - 5532:5432
    networks:
      - project107_net
    volumes:
      - project107_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=localidade

  backend:
    container_name: project107_backend
    image: jeanbarcellos/project107_backend
    depends_on:
      - database
    ports:
      - 8091:8080
    networks:
      - project107_net
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=localidade
      - LOG_SQL=false

networks:
  project107_net:
    name: project107_net
    driver: bridge
    external: false

volumes:
  project107_database_data:
    name: project107_database_data
    driver: local
